apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: chatbot-jan31-1
  janus-idp.io/tekton: chatbot-jan31-1
  backstage.io/kubernetes-id: chatbot-jan31-1
  backstage.io/kubernetes-namespace: chatbot-jan31-1
  app.kubernetes.io/part-of: chatbot-jan31-1
resources:
  - application-dev.yaml
