apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: chatbot-jan31-1-gitops
  description: This is GitOps manifest for chatbot-jan31-1   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=chatbot-jan31-1
    janus-idp.io/tekton: chatbot-jan31-1 
    backstage.io/kubernetes-id: chatbot-jan31-1 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:default/maysunfaisal 
  lifecycle: experimental
  dependsOn:
    - component:chatbot-jan31-1  
