apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: chatbot-jan31-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-jan31-1
  name: chatbot-jan31-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
